name: TOP CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  syntax:
    runs-on: ubuntu-latest
    steps:
      - name: Preuzmi kod
        uses: actions/checkout@v4
      - name: Podesi Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - name: Instaliraj zavisnosti
        run: npm install --ignore-scripts
      - name: Proveri projekat
        run: npm test
